CREATE USER ETUDIANT IDENTIFIED BY ETUDIANT;
GRANT DBA TO ETUDIANT;
CONNECT ETUDIANT/ETUDIANT
CREATE OR REPLACE PROCEDURE P_CLEANACCOUNT
IS
BEGIN
EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
FOR tuple IN (SELECT TNAME FROM TAB) LOOP
EXECUTE IMMEDIATE 'DROP TABLE '|| tuple.TNAME || ' CASCADE CONSTRAINT PURGE';
END LOOP;

FOR tuple IN (SELECT TRIGGER_NAME FROM USER_TRIGGERS) LOOP
EXECUTE IMMEDIATE 'DROP TRIGGER '|| tuple.TRIGGER_NAME;
END LOOP;

FOR tuple IN (SELECT SEQUENCE_NAME FROM USER_SEQUENCES) LOOP
EXECUTE IMMEDIATE 'DROP SEQUENCE '|| tuple.SEQUENCE_NAME;
END LOOP;

FOR tuple IN (SELECT object_name from user_procedures WHERE object_type='PROCEDURE') LOOP
IF tuple.object_name <> 'P_CLEANACCOUNT' THEN
EXECUTE IMMEDIATE 'DROP PROCEDURE '|| tuple.object_name;
END IF;
END LOOP;

FOR tuple IN (SELECT object_name from user_procedures WHERE object_type='FUNCTION') LOOP
EXECUTE IMMEDIATE 'DROP FUNCTION '|| tuple.object_name;
END LOOP;
END;
/

CALL P_CLEANACCOUNT();
CLEAR SCREEN