CONNECT SYS/oraclexe AS SYSDBA;
ALTER USER SYSTEM ACCOUNT UNLOCK;
ALTER USER SYSTEM IDENTIFIED BY oraclexe;
CONNECT SYSTEM/oraclexe;
CREATE USER ETUDIANT IDENTIFIED BY ETUDIANT;
GRANT DBA TO ETUDIANT;
CONNECT ETUDIANT/ETUDIANT
CREATE OR REPLACE PROCEDURE P_DROPALLTABLES
IS
BEGIN
EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
FOR tuple IN (SELECT TNAME, TABTYPE FROM TAB) LOOP
IF tuple.tabtype = 'TABLE' THEN
EXECUTE IMMEDIATE 'DROP TABLE '|| tuple.TNAME || ' CASCADE CONSTRAINT PURGE';
ELSE
EXECUTE IMMEDIATE 'DROP VIEW '|| tuple.TNAME;
END IF;
END LOOP;
END;
/

CALL P_DROPALLTABLES();
CLEAR SCREEN;

